---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: alertmanager-secret
    template:
      data:
        ALERTMANAGER_PUSHOVER_TOKEN: "{{ .ALERTMANAGER_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        NOTIFIARR_METRICS_KEY: "{{ .NOTIFIARR_METRICS_KEY }}"
  dataFrom:
    - extract:
        key: alertmanager
    - extract:
        key: pushover
    - extract:
        key: notifiarr
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-notifiarr-scrape
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: prometheus-notifiarr-scrape-secret
    template:
      engineVersion: v2
      data:
        notifiarr.yaml: |
          - job_name: notifiarr
            scrape_interval: 60s
            metrics_path: /metrics
            static_configs:
              - targets: ['notifiarr.media.svc.cluster.local:5454']
            http_headers:
              X-Api-Key:
                values: ["{{ .NOTIFIARR_METRICS_KEY }}"]
  dataFrom:
    - extract:
        key: notifiarr
