---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds-ready
  namespace: flux-system
spec:
  path: ./kubernetes/apps/flux-system/healthcheck/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  prune: true
  healthChecks:
    - &crds
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: replicationsources.volsync.backube
    - <<: *crds
      name: replicationdestinations.volsync.backube
    - <<: *crds
      name: externalsecrets.external-secrets.io
    - <<: *crds
      name: servicemonitors.monitoring.coreos.com
    - <<: *crds
      name: podmonitors.monitoring.coreos.com
    - <<: *crds
      name: ciliumnetworkpolicies.cilium.io
    - <<: *crds
      name: ciliumclusterwidenetworkpolicies.cilium.io
    - <<: *crds
      name: certificates.cert-manager.io
    - <<: *crds
      name: httproutes.gateway.networking.k8s.io
    - <<: *crds
      name: securitypolicies.gateway.envoyproxy.io
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-ready
  namespace: flux-system
spec:
  path: ./kubernetes/apps/flux-system/healthcheck/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: longhorn-manager
      namespace: storage
    - apiVersion: apps/v1
      kind: Deployment
      name: volsync
      namespace: volsync-system
    - &crd
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: replicationsources.volsync.backube
    - <<: *crd
      name: replicationdestinations.volsync.backube
    - <<: *crd
      name: externalsecrets.external-secrets.io
