---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: system_disk
  maxSize: 64GiB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-hostpath
provisioning:
  diskSelector:
    match: disk.model == "Corsair MP600 MINI" && !system_disk
  minSize: 1TB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn-data
provisioning:
  diskSelector:
    match: system_disk
  minSize: 850GiB
  grow: true
