# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
#
#  _______         __      ________        __      _______    _______
# |_   __ \       /  \    |_   ___ \.     /  \    |_   __ \  |_   __ \
#   | |__) |     / /\ \     | |   \. \   / /\ \     | |__) |   | |__) |
#   |  __ /     / ____ \    | |    | |  / ____ \    |  __ /    |  __ /
#  _| |  \ \_ _/ /    \ \_ _| |___.' /_/ /    \ \_ _| |  \ \_ _| |  \ \_
# |____| |___|____|  |____|________.'|____|  |____|____| |___|____| |___|
#
#
# Recyclarr Configuration Template: SQP-2-5
# Updated: 2026-02-04
radarr:
  movies-4k:
    base_url: http://radarr-4k.media.svc.cluster.local
    api_key: !env_var RADARR_4K_API_KEY

    delete_old_custom_formats: true

    quality_definition:
      type: sqp-uhd

    quality_profiles:
      - trash_id: c3933358ba2356bafc41524f81471069 # [SQP] SQP-2
        reset_unmatched_scores:
          enabled: true
      - trash_id: 2cf36c1f0106ffac993be003ade51865 # [SQP] SQP-3
        reset_unmatched_scores:
          enabled: true
      - trash_id: 013f89e6da27519fe56cf482702a2db9 # [SQP] SQP-4
        reset_unmatched_scores:
          enabled: true
      - trash_id: a7bb1539fd147256b21b1098f3dc2016 # [SQP] SQP-5
        reset_unmatched_scores:
          enabled: true

    custom_format_groups:
      add:
        - trash_id: 7fc2751eef7e6bdc70b74136e5e35c76 # [HDR Formats] DV (w/o HDR fallback)
        - trash_id: 1616617ab3a14397a2b2321bcbda44d1 # [HDR Formats] DV Boost
        - trash_id: c4492eebd0c2ddc14c2c91623aa7f95d # [Optional] Miscellaneous SQP
          select:
            - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
            - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
            - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
            - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
            - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
            - f537cf427b64c38c8e36298f657e4828 # Scene
            - f700d29429c023a5734505e77daeaea7 # DV (Disk)
            - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
            - 11cd1db7165d6a7ad9a83bc97b8b1060 # VC-1
            - ae4cfaa9283a4f2150ac3da08e388723 # VP9
            - 73613461ac2cea99d52c4cd6e177ab82 # HFR
            - 9170d55c319f4fe40da8711ba9d8050d # x265
            - 390455c22a9cac81a738f6cbad705c3c # x266
        - trash_id: 9337080378236ce4c0b183e35790d2a7 # [Optional] Miscellaneous
          select:
            - 2899d84dc9372de3408e6d8cc18e9666 # x264
        - trash_id: f4f1474b963b24cf983455743aa9906c # [Optional] Movie Versions
          select:
            - 0f12c086e289cf966fa5948eac571f44 # Hybrid
            - 570bc9ebecd92723d2d21500f4be314c # Remaster
            - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
            - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
            - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
            - e9001909a4c88013a359d0b9920d7bea # Theatrical Cut
            - 957d0f44b592285f26449575e8b1167e # Special Edition
            - eecf3a857724171f968a66cb5719e152 # IMAX
            - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        - trash_id: 47f0d69750de9e16855915fa73bb7b08 # [Optional] SDR
          select:
            - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        - trash_id: f737e18b5824d6ebb2d57b957ae2fd6c # [Streaming Services] UK

    custom_formats:
      # Raise FraMeSToR
      - trash_ids:
          - ff5bc9e8ce91d46c997ca3ac6994d6f8 # FraMeSToR
        assign_scores_to:
          - name: "[SQP] SQP-2"
          - name: "[SQP] SQP-3"
          - name: "[SQP] SQP-4"
          - name: "[SQP] SQP-5"
            score: 600
