# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
#
#  _______         __      ________        __      _______    _______
# |_   __ \       /  \    |_   ___ \.     /  \    |_   __ \  |_   __ \
#   | |__) |     / /\ \     | |   \. \   / /\ \     | |__) |   | |__) |
#   |  __ /     / ____ \    | |    | |  / ____ \    |  __ /    |  __ /
#  _| |  \ \_ _/ /    \ \_ _| |___.' /_/ /    \ \_ _| |  \ \_ _| |  \ \_
# |____| |___|____|  |____|________.'|____|  |____|____| |___|____| |___|
#
#       e      888b    | 888      e    e      888~~
#      d8b     |Y88b   | 888     d8b  d8b     888___
#     /Y88b    | Y88b  | 888    d888bdY88b    888
#    /  Y88b   |  Y88b | 888   / Y88Y Y888b   888
#   /____Y88b  |   Y88b| 888  /   YY   Y888b  888
#  /      Y88b |    Y888 888 /          Y888b 888___
#
# Recyclarr Configuration Template: Anime Radarr
# Updated: 2026-02-04
radarr:
  anime-movies:
    base_url: http://radarr-anime.media.svc.cluster.local
    api_key: !env_var RADARR_ANIME_API_KEY

    delete_old_custom_formats: true

    include:
      - template: radarr-quality-definition-anime
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime

    # Custom Formats: https://recyclarr.dev/reference/configuration/custom-formats/
    custom_formats:
      - trash_ids:
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 10 # Adjust scoring as desired

      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 10 # Adjust scoring as desired

      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 10 # Adjust scoring as desired
