# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
#
#  _______         __      ________        __      _______    _______
# |_   __ \       /  \    |_   ___ \.     /  \    |_   __ \  |_   __ \
#   | |__) |     / /\ \     | |   \. \   / /\ \     | |__) |   | |__) |
#   |  __ /     / ____ \    | |    | |  / ____ \    |  __ /    |  __ /
#  _| |  \ \_ _/ /    \ \_ _| |___.' /_/ /    \ \_ _| |  \ \_ _| |  \ \_
# |____| |___|____|  |____|________.'|____|  |____|____| |___|____| |___|
#
#
# Recyclarr Configuration Template: SQP-2-5
# Updated: 2026-02-04
radarr:
  movies-4k:
    base_url: http://radarr-4k.media.svc.cluster.local
    api_key: !env_var RADARR_4K_API_KEY

    delete_old_custom_formats: true

    quality_definition:
      type: sqp-uhd

    quality_profiles:
      - trash_id: c3933358ba2356bafc41524f81471069 # [SQP] SQP-2
        reset_unmatched_scores:
          enabled: true
      - trash_id: 2cf36c1f0106ffac993be003ade51865 # [SQP] SQP-3
        reset_unmatched_scores:
          enabled: true
      - trash_id: 013f89e6da27519fe56cf482702a2db9 # [SQP] SQP-4
        reset_unmatched_scores:
          enabled: true
      - trash_id: a7bb1539fd147256b21b1098f3dc2016 # [SQP] SQP-5
        reset_unmatched_scores:
          enabled: true

    custom_format_groups:
      add:
        - trash_id: 7fc2751eef7e6bdc70b74136e5e35c76 # [HDR Formats] DV (w/o HDR fallback)
        - trash_id: 1616617ab3a14397a2b2321bcbda44d1 # [HDR Formats] DV Boost
        # - trash_id: b29413a7487478fe98228ce79e5689e4  # [HDR Formats] HDR10+ Boost
        - trash_id: c4492eebd0c2ddc14c2c91623aa7f95d # [Optional] Miscellaneous SQP
        - trash_id: f4f1474b963b24cf983455743aa9906c # [Optional] Movie Versions
        - trash_id: 47f0d69750de9e16855915fa73bb7b08 # [Optional] SDR
        # - trash_id: b22449f789b16a4163b59f1b70cbc580  # [Streaming Services] Asian
        # - trash_id: 088a792e0561c927fb396664b0db5c8f  # [Streaming Services] Dutch
        - trash_id: 9fc645b3cef52b149ec13ba3972245d1 # [Streaming Services] Miscellaneous
        - trash_id: f737e18b5824d6ebb2d57b957ae2fd6c # [Streaming Services] UK
