# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
#
#  _______         __      ________        __      _______    _______
# |_   __ \       /  \    |_   ___ \.     /  \    |_   __ \  |_   __ \
#   | |__) |     / /\ \     | |   \. \   / /\ \     | |__) |   | |__) |
#   |  __ /     / ____ \    | |    | |  / ____ \    |  __ /    |  __ /
#  _| |  \ \_ _/ /    \ \_ _| |___.' /_/ /    \ \_ _| |  \ \_ _| |  \ \_
# |____| |___|____|  |____|________.'|____|  |____|____| |___|____| |___|
#
#
# Recyclarr Configuration Template: SQP-1 (1080p)
# Updated: 2026-02-04
# Recyclarr Configuration Template: SQP-1 (2160p)
# Updated: 2026-02-04
radarr:
  movies:
    base_url: http://radarr.media.svc.cluster.local
    api_key: !env_var RADARR_API_KEY

    delete_old_custom_formats: true

    include:
      # Quality sizes (only needed once)
      - template: radarr-quality-definition-sqp-streaming
      # SQP-1 (1080p)
      - template: radarr-quality-profile-sqp-1-1080p
      - template: radarr-custom-formats-sqp-1-1080p
      # SQP-1 (2160p)
      - template: radarr-quality-profile-sqp-1-2160p-imax-e
      - template: radarr-quality-profile-sqp-1-2160p-default

    quality_profiles:
      - name: SQP-1 (2160p)
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray|WEB-2160p
          until_score: 10000
        min_format_score: 1000
        score_set: sqp-1-2160p
        quality_sort: top
        qualities:
          - name: Bluray|WEB-2160p
            qualities:
              - Bluray-2160p
              - WEBDL-2160p
              - WEBRip-2160p

    custom_formats:
      # Movie Versions
      - trash_ids:
          # Uncomment any of the next six lines to prefer these movie versions
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
          # Optional
          # HDR10+ Boost - Uncomment the HDR10+ Boost line if you want to prefer HDR10+ releases
          # DV Boost - Uncomment the DV Boost line if you want to prefer DV releases
          # Uncomment both lines if you want to prefer both (DV HDR10+)
          - b337d6812e06c200ec9a2d3cfa9d20a7 # DV Boost
          # - caa37d0df9c348912df1fb1d88f9273a # HDR10+ Boost

          # Comment out the next line if you and all of your users' setups are fully DV compatible
          - 923b6abef9b17f937fab56cfcf89e1f1 # DV (w/o HDR fallback)

          # Uncomment any of the following if you want them to be added to the quality profile
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
          - f700d29429c023a5734505e77daeaea7 # DV (Disk)
        assign_scores_to:
          - name: SQP-1 (1080p)
          - name: SQP-1 (2160p)
      # Unwanted
      - trash_ids:
          # Uncomment the next six lines to block all x265 HD releases
          - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
        assign_scores_to:
          - name: SQP-1 (2160p)
            score: 0
      - trash_ids:
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        assign_scores_to:
          - name: SQP-1 (2160p)
      # Optional SDR
      # Only ever use ONE of the following custom formats:
      # SDR - block ALL SDR releases
      # SDR (no WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
      - trash_ids:
          - 9c38ebb7384dada637be8899efa68e6f # SDR
          # - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        assign_scores_to:
          - name: SQP-1 (2160p)
      - trash_ids:
          - cae4ca30163749b891686f95532519bd # AV1
        assign_scores_to:
          - name: SQP-1 (2160p)
            # score: 0 # Uncomment this line to allow AV1 releases
      # Lower BHDStudio
      - trash_ids:
          - 5153ec7413d9dae44e24275589b5e944 # BHDStudio
        assign_scores_to:
          - name: SQP-1 (1080p)
          - name: SQP-1 (2160p)
            score: 600
      # Raise hallowed
      - trash_ids:
          - 7a0d1ad358fee9f5b074af3ef3f9d9ef # hallowed
        assign_scores_to:
          - name: SQP-1 (1080p)
          - name: SQP-1 (2160p)
            score: 1000
