# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
#
#  _______         __      ________        __      _______    _______
# |_   __ \       /  \    |_   ___ \.     /  \    |_   __ \  |_   __ \
#   | |__) |     / /\ \     | |   \. \   / /\ \     | |__) |   | |__) |
#   |  __ /     / ____ \    | |    | |  / ____ \    |  __ /    |  __ /
#  _| |  \ \_ _/ /    \ \_ _| |___.' /_/ /    \ \_ _| |  \ \_ _| |  \ \_
# |____| |___|____|  |____|________.'|____|  |____|____| |___|____| |___|
#
#       e      888b    | 888      e    e      888~~
#      d8b     |Y88b   | 888     d8b  d8b     888___
#     /Y88b    | Y88b  | 888    d888bdY88b    888
#    /  Y88b   |  Y88b | 888   / Y88Y Y888b   888
#   /____Y88b  |   Y88b| 888  /   YY   Y888b  888
#  /      Y88b |    Y888 888 /          Y888b 888___
#
# Recyclarr Configuration Template: Anime Radarr
# Updated: 2026-02-04
radarr:
  anime-movies:
    base_url: http://radarr-anime.media.svc.cluster.local
    api_key: !env_var RADARR_ANIME_API_KEY

    delete_old_custom_formats: true

    quality_definition:
      type: anime

    quality_profiles:
      - trash_id: 722b624f9af1e492284c4bc842153a38 # [Anime] Remux-1080p
        reset_unmatched_scores:
          enabled: true

    custom_format_groups:
      add:
        - trash_id: 9337080378236ce4c0b183e35790d2a7 # [Optional] Miscellaneous
        - trash_id: b22449f789b16a4163b59f1b70cbc580 # [Streaming Services] Asian
        # - trash_id: 088a792e0561c927fb396664b0db5c8f  # [Streaming Services] Dutch
        - trash_id: 9fc645b3cef52b149ec13ba3972245d1 # [Streaming Services] Miscellaneous
        - trash_id: f737e18b5824d6ebb2d57b957ae2fd6c # [Streaming Services] UK
