# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
#
#  _______         __      ________        __      _______    _______
# |_   __ \       /  \    |_   ___ \.     /  \    |_   __ \  |_   __ \
#   | |__) |     / /\ \     | |   \. \   / /\ \     | |__) |   | |__) |
#   |  __ /     / ____ \    | |    | |  / ____ \    |  __ /    |  __ /
#  _| |  \ \_ _/ /    \ \_ _| |___.' /_/ /    \ \_ _| |  \ \_ _| |  \ \_
# |____| |___|____|  |____|________.'|____|  |____|____| |___|____| |___|
#
#       e      888b    | 888      e    e      888~~
#      d8b     |Y88b   | 888     d8b  d8b     888___
#     /Y88b    | Y88b  | 888    d888bdY88b    888
#    /  Y88b   |  Y88b | 888   / Y88Y Y888b   888
#   /____Y88b  |   Y88b| 888  /   YY   Y888b  888
#  /      Y88b |    Y888 888 /          Y888b 888___
#
# Recyclarr Configuration Template: Anime Radarr
# Updated: 2026-02-04
radarr:
  anime-movies:
    base_url: http://radarr-anime.media.svc.cluster.local
    api_key: !env_var RADARR_ANIME_API_KEY

    delete_old_custom_formats: true

    quality_definition:
      type: anime

    quality_profiles:
      - trash_id: 722b624f9af1e492284c4bc842153a38 # [Anime] Remux-1080p
        reset_unmatched_scores:
          enabled: true

    custom_format_groups:
      add:
        - trash_id: 9337080378236ce4c0b183e35790d2a7 # [Optional] Miscellaneous
          select:
            - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
            - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
            - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
            - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
            - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
            - f537cf427b64c38c8e36298f657e4828 # Scene
            - f700d29429c023a5734505e77daeaea7 # DV (Disk)
            - 11cd1db7165d6a7ad9a83bc97b8b1060 # VC-1
            - ae4cfaa9283a4f2150ac3da08e388723 # VP9
            - 73613461ac2cea99d52c4cd6e177ab82 # HFR
            - 2899d84dc9372de3408e6d8cc18e9666 # x264
            - 9170d55c319f4fe40da8711ba9d8050d # x265
            - 390455c22a9cac81a738f6cbad705c3c # x266
        - trash_id: 60f6d50cbd3cfc3e9a8c00e3a30c3114 # [Streaming Services] Anime
        - trash_id: b22449f789b16a4163b59f1b70cbc580 # [Streaming Services] Asian
        - trash_id: f737e18b5824d6ebb2d57b957ae2fd6c # [Streaming Services] UK
