# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
#
#  _______         __      ________        __      _______    _______
# |_   __ \       /  \    |_   ___ \.     /  \    |_   __ \  |_   __ \
#   | |__) |     / /\ \     | |   \. \   / /\ \     | |__) |   | |__) |
#   |  __ /     / ____ \    | |    | |  / ____ \    |  __ /    |  __ /
#  _| |  \ \_ _/ /    \ \_ _| |___.' /_/ /    \ \_ _| |  \ \_ _| |  \ \_
# |____| |___|____|  |____|________.'|____|  |____|____| |___|____| |___|
#
#
# Recyclarr Configuration Template: SQP-1 (1080p)
# Updated: 2026-02-04
# Recyclarr Configuration Template: SQP-1 (2160p)
# Updated: 2026-02-04
radarr:
  movies:
    base_url: http://radarr.media.svc.cluster.local
    api_key: !env_var RADARR_API_KEY

    delete_old_custom_formats: true

    quality_definition:
      type: sqp-streaming

    quality_profiles:
      - trash_id: 90a3370d2d30cbaf08d9c23b856a12c8 # [SQP] SQP-1 WEB (1080p)
        reset_unmatched_scores:
          enabled: true
      - trash_id: e91c9adaca0231493f4af0d571b907f9 # [SQP] SQP-1 WEB (2160p)
        reset_unmatched_scores:
          enabled: true
      - name: SQP-1 (2160p)
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray|WEB-2160p
          until_score: 10000
        min_format_score: 1000
        score_set: sqp-1-2160p
        quality_sort: top
        qualities:
          - name: Bluray|WEB-2160p
            qualities:
              - Bluray-2160p
              - WEBDL-2160p
              - WEBRip-2160p

    custom_format_groups:
      add:
        - trash_id: 7fc2751eef7e6bdc70b74136e5e35c76 # [HDR Formats] DV (w/o HDR fallback)
        - trash_id: 1616617ab3a14397a2b2321bcbda44d1 # [HDR Formats] DV Boost
        - trash_id: 9337080378236ce4c0b183e35790d2a7 # [Optional] Miscellaneous
        - trash_id: f4f1474b963b24cf983455743aa9906c # [Optional] Movie Versions
        # - trash_id: b22449f789b16a4163b59f1b70cbc580  # [Streaming Services] Asian
        # - trash_id: 088a792e0561c927fb396664b0db5c8f  # [Streaming Services] Dutch
        - trash_id: 9fc645b3cef52b149ec13ba3972245d1 # [Streaming Services] Miscellaneous
        - trash_id: f737e18b5824d6ebb2d57b957ae2fd6c # [Streaming Services] UK

    custom_formats:
      # Lower BHDStudio
      - trash_ids:
          - 5153ec7413d9dae44e24275589b5e944 # BHDStudio
        assign_scores_to:
          - name: SQP-1 (1080p)
          - name: SQP-1 (2160p)
            score: 600
      # Raise hallowed
      - trash_ids:
          - 7a0d1ad358fee9f5b074af3ef3f9d9ef # hallowed
        assign_scores_to:
          - name: SQP-1 (1080p)
          - name: SQP-1 (2160p)
            score: 1000
