# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
#
#   _______   ____   ____  _____      __      _______    _______
#  /  ___  |.'    \.|_   \|_   _|    /  \    |_   __ \  |_   __ \
# |  (__ \_|  .--.  \ |   \ | |     / /\ \     | |__) |   | |__) |
#  '.___\-.| |    | | | |\ \| |    / ____ \    |  __ /    |  __ /
# |\\____) |  \--'  /_| |_\   |_ _/ /    \ \_ _| |  \ \_ _| |  \ \_
# |_______.'\.____.'|_____|\____|____|  |____|____| |___|____| |___|
#
#
# Recyclarr Configuration Template: WEB-1080p (V4)
# Updated: 2026-02-04
# Recyclarr Configuration Template: WEB-2160p (V4)
# Updated: 2026-02-04
sonarr:
  tv:
    base_url: http://sonarr.media.svc.cluster.local
    api_key: !env_var SONARR_API_KEY

    quality_definition:
      type: series

    quality_profiles:
      - trash_id: c4cadd6b35b95f62c3d47a408e53e2f7 # WEB-2160p (Combined)
        reset_unmatched_scores:
          enabled: true

    custom_format_groups:
      add:
        - trash_id: e9a1944a254e6f8a9da63083f7ae15cb # [Audio] Audio Formats
        - trash_id: d776a1ea912a117d66d83b880ff2055d # [HDR Formats] DV (w/o HDR fallback)
        - trash_id: e0b2774083df4265f25c9e5bc6c80940 # [HDR Formats] DV Boost
        - trash_id: 7d366c213e5c23a052b157356fac1921 # [HDR Formats] HDR10+ Boost
        - trash_id: f4a0410a1df109a66d6e47dcadcce014 # [Optional] Miscellaneous
        - trash_id: e1053c0ef622df3749fa43c22865663a # [Optional] SDR
        - trash_id: d920fd959d220306888f40b6f38e1578 # [Optional] Season Packs
        - trash_id: 35fb4585dcd9e2a5ac732e4309f5a45a # [Streaming Services] Asian
        - trash_id: f60f4401ce880aad62e9d21c8bb6b91a # [Streaming Services] Dutch
        - trash_id: 848fd356c200568fc5a6248150e7e7ea # [Streaming Services] French
        - trash_id: 7832db22b71ab669458c17a2850d6913 # [Streaming Services] Miscellaneous
        - trash_id: ddab3095a5d2f436f369263840af34f9 # [Streaming Services] UK
