# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
#
#   _______   ____   ____  _____      __      _______    _______
#  /  ___  |.'    \.|_   \|_   _|    /  \    |_   __ \  |_   __ \
# |  (__ \_|  .--.  \ |   \ | |     / /\ \     | |__) |   | |__) |
#  '.___\-.| |    | | | |\ \| |    / ____ \    |  __ /    |  __ /
# |\\____) |  \--'  /_| |_\   |_ _/ /    \ \_ _| |  \ \_ _| |  \ \_
# |_______.'\.____.'|_____|\____|____|  |____|____| |___|____| |___|
#
#       e      888b    | 888      e    e      888~~
#      d8b     |Y88b   | 888     d8b  d8b     888___
#     /Y88b    | Y88b  | 888    d888bdY88b    888
#    /  Y88b   |  Y88b | 888   / Y88Y Y888b   888
#   /____Y88b  |   Y88b| 888  /   YY   Y888b  888
#  /      Y88b |    Y888 888 /          Y888b 888___
#
# Recyclarr Configuration Template: Anime Sonarr
# Updated: 2026-02-04
sonarr:
  anime:
    base_url: http://sonarr-anime.media.svc.cluster.local
    api_key: !env_var SONARR_ANIME_API_KEY

    delete_old_custom_formats: true

    quality_definition:
      type: anime

    quality_profiles:
      - trash_id: 20e0fc959f1f1704bed501f23bdae76f # [Anime] Remux-1080p
        reset_unmatched_scores:
          enabled: true

    custom_format_groups:
      add:
        - trash_id: f4a0410a1df109a66d6e47dcadcce014 # [Optional] Miscellaneous
        - trash_id: 35fb4585dcd9e2a5ac732e4309f5a45a # [Streaming Services] Asian
        - trash_id: f60f4401ce880aad62e9d21c8bb6b91a # [Streaming Services] Dutch
        - trash_id: 848fd356c200568fc5a6248150e7e7ea # [Streaming Services] French
        - trash_id: 7832db22b71ab669458c17a2850d6913 # [Streaming Services] Miscellaneous
        - trash_id: ddab3095a5d2f436f369263840af34f9 # [Streaming Services] UK
