# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
#
#   _______   ____   ____  _____      __      _______    _______
#  /  ___  |.'    \.|_   \|_   _|    /  \    |_   __ \  |_   __ \
# |  (__ \_|  .--.  \ |   \ | |     / /\ \     | |__) |   | |__) |
#  '.___\-.| |    | | | |\ \| |    / ____ \    |  __ /    |  __ /
# |\\____) |  \--'  /_| |_\   |_ _/ /    \ \_ _| |  \ \_ _| |  \ \_
# |_______.'\.____.'|_____|\____|____|  |____|____| |___|____| |___|
#
#       e      888b    | 888      e    e      888~~
#      d8b     |Y88b   | 888     d8b  d8b     888___
#     /Y88b    | Y88b  | 888    d888bdY88b    888
#    /  Y88b   |  Y88b | 888   / Y88Y Y888b   888
#   /____Y88b  |   Y88b| 888  /   YY   Y888b  888
#  /      Y88b |    Y888 888 /          Y888b 888___
#
# Recyclarr Configuration Template: Anime Sonarr
# Updated: 2026-02-04
sonarr:
  anime:
    base_url: http://sonarr-anime.media.svc.cluster.local
    api_key: !env_var SONARR_ANIME_API_KEY

    delete_old_custom_formats: true

    include:
      - template: sonarr-quality-definition-anime
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime

    custom_formats:
      - trash_ids:
          # Anime Optional
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        assign_scores_to:
          - { name: Remux-1080p - Anime, score: 10 }
      - trash_ids:
          - 9c14d194486c4014d422adc64092d794 # Dubs Only
          - 07a32f77690263bb9fda1842db7e273f # VOSTFR
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          - { name: Remux-1080p - Anime, score: -10000 }
