---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube
spec:
  chartRef:
    kind: OCIRepository
    name: node-feature-discovery
  interval: 1h
  values:
    worker:
      config:
        core:
          labelSources: ["custom", "cpu", "pci", "usb", "system"]
        sources:
          usb:
            deviceClassWhitelist:
              ["00", "03", "0B", "0e", "10", "ef", "fe", "ff"]
            deviceLabelFields: ["class", "vendor", "device"]
          custom:
            - name: "baremetal"
              labels:
                "feature.node.kubernetes.io/baremetal": "true"
              matchFeatures:
                - feature: cpu.cpuid
                  matchExpressions:
                    HYPERVISOR: { op: DoesNotExist }
    prometheus:
      enable: true
