---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kopia
  namespace: volsync-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/nfs-scaler
  path: ./kubernetes/apps/volsync-system/kopia/app
  postBuild:
    substitute:
      APP: kopia
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  wait: false
  prune: true
  dependsOn:
    - name: volsync
