---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app notifiarr
  namespace: media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/media/notifiarr/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 5m
  prune: true
  timeout: 5m
  wait: true
  dependsOn:
    - name: external-secrets-store
      namespace: security
    - name: rook-ceph-cluster
      namespace: rook-ceph
  postBuild:
    substitute:
      APP: *app
      PVC_NAME: config
      GATUS_SUBDOMAIN: notifiarr
      PVC_CAPACITY: 10Gi
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_SCHEDULE: ${NOTIFIARR_CONFIG_VOLSYNC_SCHEDULE}
