---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: authentik-secret
    template:
      data:
        # Redis settings
        AUTHENTIK_REDIS__DB: "1"
        # Authentik bootstrap
        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .AUTHENTIK_BOOTSTRAP_EMAIL }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .AUTHENTIK_BOOTSTRAP_PASS }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .AUTHENTIK_TOKEN }}"
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        # Email settings
        EMAIL_SERVER: "{{ .EMAIL_SERVER }}"
        EMAIL_USER: "{{ .EMAIL_USER }}"
        EMAIL_FROM: "Authentik <{{ .EMAIL_FROM }}>"
        EMAIL_PASS: "{{ .EMAIL_PASS }}"
        # Media S3 settings
        AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT: "https://{{ .B2_ENDPOINT }}"
        AUTHENTIK_STORAGE__MEDIA__S3__REGION: "{{ .AUTHENTIK_STORAGE_MEDIA_S3_REGION }}"
        AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY: "{{ .AWS_ACCESS_KEY_ID }}"
        AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME: "{{ .AUTHENTIK_MEDIA_BUCKET_NAME }}"
        AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN: "{{ .B2_ENDPOINT }}/{{ .AUTHENTIK_MEDIA_BUCKET_NAME }}"
        # GeoIP settings
        AUTHENTIK_GEOIP_ACCOUNT_ID: "{{ .AUTHENTIK_GEOIP_ACCOUNT_ID }}"
        AUTHENTIK_GEOIP_LICENSE_KEY: "{{ .AUTHENTIK_GEOIP_LICENSE_KEY }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: email
    - extract:
        key: volsync_s3_template
