---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-nebula-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: pihole-nebula-sync-secret
    template:
      data:
        PRIMARY: 'http://pi-0.internal.|{{ .PASSWORD }}'
        REPLICAS: 'http://pi-1.internal.|{{ .PASSWORD }}'
  dataFrom:
    - extract:
        key: pihole
