---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pihole-nebula-sync
  namespace: network
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: pihole-nebula-sync
  values:
    defaultPodOptions:
      priorityClassName: system-cluster-critical
      hostUsers: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          *app :
            image:
              repository: ghcr.io/lovelaze/nebula-sync
              tag: v0.11.1@sha256:e6bb9ac7dbf4471b066cb5db74929c6fa7cfa2251a0682fa85f6da8f687ba4bf
            env:
              FULL_SYNC: "false"
              RUN_GRAVITY: "false"
              CRON: "*/10 * * * *"
              CLIENT_SKIP_TLS_VERIFICATION: "true"
              TZ: ${TIMEZONE}
              SYNC_CONFIG_DNS: "true"
              SYNC_CONFIG_DHCP: "false"
              SYNC_CONFIG_NTP: "true"
              SYNC_CONFIG_RESOLVER: "false"
              SYNC_CONFIG_DATABASE: "false"
              SYNC_CONFIG_MISC: "true"
              SYNC_CONFIG_DEBUG: "true"
              SYNC_GRAVITY_DHCP_LEASES: "false"
              SYNC_GRAVITY_GROUP: "false"
              SYNC_GRAVITY_AD_LIST: "true"
              SYNC_GRAVITY_AD_LIST_BY_GROUP: "true"
              SYNC_GRAVITY_DOMAIN_LIST: "true"
              SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP: "true"
              SYNC_GRAVITY_CLIENT: "false"
              SYNC_GRAVITY_CLIENT_BY_GROUP: "false"
              API_ENABLED: "true"
            envFrom:
              - secretRef:
                  name: pihole-nebula-sync-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFileSystem: true
              capabilities: { drop: ['ALL'] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
