---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
# this secret gets manually created at bootstrap, and then this takes control of it
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name bitwarden-access-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 1m
  target:
    name: *name
  # this can NOT end in a newline or it doesn't work
  data:
    - secretKey: token
      remoteRef:
        key: "c172e0f9-9530-48c3-9591-b32800e543cc"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
# this secret gets manually created at bootstrap, and then this takes control of it
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-access-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  refreshInterval: 1m
  target:
    name: bitwarden-access-token-secret
    template:
      data:
        token: "{{ .BITWARDEN_AUTH_TOKEN_RW }}"
  # this can NOT end in a newline or it doesn't work
  dataFrom:
    - extract:
        key: bitwarden
