---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-crds
  namespace: database
spec:
  path: ./kubernetes/apps/database/cnpg/crds
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  prune: true
  healthChecks:
    - &crds
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusters.postgresql.cnpg.io
    - <<: *crds
      apiVersion: apiextensions.k8s.io/v1
      name: objectstores.barmancloud.cnpg.io
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: database
spec:
  path: ./kubernetes/apps/database/cnpg/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  prune: true
  wait: true
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plugin-barman-cloud
  namespace: database
spec:
  path: ./kubernetes/apps/database/cnpg/plugin-barman-cloud
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  prune: true
  wait: true
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app postgres-cluster
  namespace: &namespace database
spec:
  path: ./kubernetes/apps/database/cnpg/cluster
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  prune: true
  dependsOn:
    - name: cnpg-crds
      namespace: database
    - name: storage-ready
      namespace: flux-system
  components:
    - ../../../../components/cnpg/backup
  postBuild:
    substitute:
      APP: cluster
      CNPG_IMAGE: ghcr.io/cloudnative-pg/postgresql:18.1-standard-trixie@sha256:f445b2f8e9b4b3b9a4df56d944c976a2d7eb9b50280f3a6986b0fc7c422f7f27
      CNPG_REPLICAS: '2'
      CNPG_SIZE: 5Gi
      CNPG_LIMITS_MEMORY_HUGEPAGES: 1Gi
      CNPG_LIMITS_MEMORY: 2Gi
  healthChecks:
    - apiVersion: &postgresVersion postgresql.cnpg.io/v1
      kind: &postgresKind Cluster
      name: *app
      namespace: *namespace
  healthCheckExprs:
    - apiVersion: *postgresVersion
      kind: *postgresKind
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pgadmin
  namespace: database
spec:
  path: ./kubernetes/apps/database/cnpg/pgadmin
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  prune: true
  components:
    - ../../../../components/common
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *app
      PVC_NAME: config
      GATUS_SUBDOMAIN: pgadmin
      PVC_CAPACITY: 10Gi
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_SCHEDULE: ${PGADMIN_CONFIG_VOLSYNC_SCHEDULE}
