---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app emby
  namespace: media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/nfs-scaler
    - ../../../../components/volsync
  path: ./kubernetes/apps/media/emby/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 5m
  prune: true
  timeout: 5m
  wait: true
  dependsOn:
    - name: intel-gpu-resource-driver
      namespace: kube-system
    - name: storage-ready
      namespace: flux-system
  postBuild:
    substitute:
      APP: *app
      PVC_NAME: config
      GATUS_SUBDOMAIN: emby
      PVC_CAPACITY: 100Gi
      VOLSYNC_CAPACITY: 100Gi
      VOLSYNC_SCHEDULE: ${EMBY_CONFIG_VOLSYNC_SCHEDULE}
