---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./exporters/ks.yaml
  - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  - ./headlamp/ks.yaml
  - ./keda/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./victoria-logs/ks.yaml
