node_exporter_enabled: true
smartctl_exporter_enabled: true

# renovate: datasource=github-releases depName=prometheus/node_exporter
node_exporter_version: "1.10.2"
# renovate: datasource=github-releases depName=prometheus-community/smartctl_exporter
smartctl_exporter_version: "0.14.0"
