---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notifiarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: notifiarr-secret
    template:
      data:
        DN_API_KEY: "{{ .NOTIFIARR_API_KEY }}"
        DN_LIDARR_0_API_KEY: "{{ .LIDARR_API_KEY }}"
        DN_PROWLARR_0_API_KEY: "{{ .PROWLARR_API_KEY }}"
        DN_RADARR_0_API_KEY: "{{ .RADARR_API_KEY }}"
        DN_RADARR_1_API_KEY: "{{ .RADARR_4K_API_KEY }}"
        DN_RADARR_2_API_KEY: "{{ .RADARR_ANIME_API_KEY }}"
        DN_READARR_0_API_KEY: "{{ .READARR_API_KEY }}"
        DN_SONARR_0_API_KEY: "{{ .SONARR_API_KEY }}"
        DN_SONARR_1_API_KEY: "{{ .SONARR_ANIME_API_KEY }}"
        DN_SABNZBD_0_API_KEY: "{{ .SABNZBD_API_KEY }}"
        DN_PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        DN_TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"
  dataFrom:
    - extract:
        key: notifiarr
    - extract:
        key: lidarr
    - extract:
        key: prowlarr
    - extract:
        key: radarr
    - extract:
        key: readarr
    - extract:
        key: sonarr
    - extract:
        key: sabnzbd
    - extract:
        key: plex
    - extract:
        key: tautulli
