---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app notifiarr
spec:
  chartRef:
    kind: OCIRepository
    name: notifiarr
  interval: 1h
  values:
    controllers:
      notifiarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            nameOverride: *app
            image:
              repository: ghcr.io/notifiarr/notifiarr
              tag: v0.9.1@sha256:10c9d20bc359f61d610461c11fb3b719cee75b7d4a0d8a3e5b3d00b9a31c48dd
            env:
              DN_UPSTREAMS_0: "[10.42.0.0/16,10.43.0.0/16,192.168.0.0/16]"
              TMPDIR: /tmp
              DN_LOG_FILE: "/config/logs/notifiarr.log"
              DN_HTTP_LOG: "/config/logs/http.log"
              DN_SERVICES_LOG_FILE: "/config/logs/services.log"
              DN_LOG_FILE_MB: "10"
              DN_LOG_FILES: "5"
              DN_FILE_MODE: "0600"
              DN_TIMEOUT: "60s"
              # Lidarr Configuration
              DN_LIDARR_0_NAME: "Lidarr"
              DN_LIDARR_0_URL: http://lidarr.media.svc.cluster.local
              DN_LIDARR_0_INTERVAL: 5m
              DN_LIDARR_0_TIMEOUT: 15s
              # Prowlarr Configuration
              DN_PROWLARR_0_NAME: "Prowlarr"
              DN_PROWLARR_0_URL: http://prowlarr.media.svc.cluster.local
              DN_PROWLARR_0_INTERVAL: 5m
              DN_PROWLARR_0_TIMEOUT: 15s
              # Radarr Configuration
              DN_RADARR_0_NAME: "Radarr"
              DN_RADARR_0_URL: http://radarr.media.svc.cluster.local
              DN_RADARR_0_INTERVAL: 5m
              DN_RADARR_0_TIMEOUT: 15s
              DN_RADARR_1_NAME: "Radarr-4k"
              DN_RADARR_1_URL: http://radarr-4k.media.svc.cluster.local
              DN_RADARR_1_INTERVAL: 5m
              DN_RADARR_1_TIMEOUT: 15s
              DN_RADARR_2_NAME: "Radarr-Anime"
              DN_RADARR_2_URL: http://radarr-anime.media.svc.cluster.local
              DN_RADARR_2_INTERVAL: 5m
              DN_RADARR_2_TIMEOUT: 15s
              # Readarr Configuration
              DN_READARR_0_NAME: "Readarr"
              DN_READARR_0_URL: http://readarr.media.svc.cluster.local
              DN_READARR_0_INTERVAL: 5m
              DN_READARR_0_TIMEOUT: 15s
              # Sonarr Configuration
              DN_SONARR_0_NAME: "Sonarr"
              DN_SONARR_0_URL: http://sonarr.media.svc.cluster.local
              DN_SONARR_0_INTERVAL: 5m
              DN_SONARR_0_TIMEOUT: 15s
              DN_SONARR_1_NAME: "Sonarr-Anime"
              DN_SONARR_1_URL: http://sonarr-anime.media.svc.cluster.local
              DN_SONARR_1_INTERVAL: 5m
              DN_SONARR_1_TIMEOUT: 15s
              # qBittorrent Configuration
              DN_QBIT_0_NAME: "qBittorrent"
              DN_QBIT_0_URL: http://qbittorrent.torrents.svc.cluster.local
              DN_QBIT_0_INTERVAL: 5m
              DN_QBIT_0_TIMEOUT: 60s
              # SABnzbd Configuration
              DN_SABNZBD_0_NAME: "SABnzbd"
              DN_SABNZBD_0_URL: http://sabnzbd.media.svc.cluster.local
              DN_SABNZBD_0_INTERVAL: 5m
              DN_SABNZBD_0_TIMEOUT: 15s
              # Plex Configuration
              DN_PLEX_URL: http://plex.media.svc.cluster.local:32400
              DN_PLEX_INTERVAL: 5m
              DN_PLEX_TIMEOUT: 15s
              # Tautulli Configuration
              DN_TAUTULLI_NAME: "Tautulli"
              DN_TAUTULLI_URL: http://tautulli.media.svc.cluster.local:8181
              DN_TAUTULLI_INTERVAL: 5m
              DN_TAUTULLI_TIMEOUT: 15s
            envFrom:
              - secretRef:
                  name: notifiarr-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      hostname: notifiarr-talos
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        annotations:
          lbipam.cilium.io/ips: "${NOTIFIARR_IP:=192.168.10.113}"
        ports:
          http:
            port: &port 5454
    route:
      app:
        hostnames:
          - "notifiarr.${SECRET_DOMAIN:=flux.local}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      tmp:
        type: emptyDir
        medium: Memory
