---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app recyclarr
spec:
  chartRef:
    kind: OCIRepository
    name: recyclarr
  interval: 1h
  values:
    controllers:
      recyclarr:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            nameOverride: *app
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 8.2.1@sha256:791bdc0d2a35b0f24b89a0b14159591269ef070f19fcccfc5fb518a863141373
            env:
              CRON_SCHEDULE: "@daily"
              RECYCLARR_CREATE_CONFIG: "true"
              TZ: ${TIMEZONE:-Etc/UTC}
            envFrom:
              - secretRef:
                  name: recyclarr-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      configs-dir:
        type: emptyDir
        globalMounts:
          - path: /config/configs
      configs:
        type: configMap
        name: recyclarr-configs
        advancedMounts:
          recyclarr:
            app:
              - path: /config/configs/radarr-4k.yaml
                subPath: radarr-4k.yaml
                readOnly: true
              - path: /config/configs/radarr-anime.yaml
                subPath: radarr-anime.yaml
                readOnly: true
              - path: /config/configs/radarr.yaml
                subPath: radarr.yaml
                readOnly: true
              - path: /config/configs/sonarr-anime.yaml
                subPath: sonarr-anime.yaml
                readOnly: true
              - path: /config/configs/sonarr.yaml
                subPath: sonarr.yaml
                readOnly: true
      includes:
        type: configMap
        name: recyclarr-includes
        advancedMounts:
          recyclarr:
            app:
              - path: /config/configs/includes/sonarr/web-720p-v4.yaml
                subPath: web-720p-v4.yaml
                readOnly: true
      custom-formats:
        type: configMap
        name: recyclarr-custom-formats
        advancedMounts:
          recyclarr:
            app:
              - path: /config/configs/custom_formats/sonarr/!bhdstudio.json
                subPath: bhdstudio.json
                readOnly: true
              - path: /config/configs/custom_formats/sonarr/!not-original-language.json
                subPath: not-original-language.json
                readOnly: true
              - path: /config/configs/custom_formats/sonarr/!uhd-bluray-tier-01.json
                subPath: uhd-bluray-tier-01.json
                readOnly: true
