---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: cross-seed-secret
    template:
      data:
        config.js: |
          module.exports = {
            action: "inject",
            apiKey: "{{.CROSS_SEED_API_KEY}}",
            useClientTorrents: true,
            torrentClients: ["qbittorrent:http://qbittorrent.torrents.svc.cluster.local."],
            radarr: [
              "http://radarr.media.svc.cluster.local./?apikey={{ .RADARR_API_KEY }}",
              "http://radarr-anime.media.svc.cluster.local./?apikey={{ .RADARR_ANIME_API_KEY }}",
              "http://radarr-4k.media.svc.cluster.local./?apikey={{ .RADARR_4K_API_KEY }}"
              ],
            sonarr: [
              "http://sonarr.media.svc.cluster.local./?apikey={{ .SONARR_API_KEY }}",
              "http://sonarr-anime.media.svc.cluster.local./?apikey={{ .SONARR_ANIME_API_KEY }}"
              ],
            torznab: [
              //"http://prowlarr.media.svc.cluster.local/3/api?apikey={{ .PROWLARR_API_KEY }}",  // Nebulance
              "http://prowlarr.media.svc.cluster.local/10/api?apikey={{ .PROWLARR_API_KEY }}", // MoreThanTV
              "http://prowlarr.media.svc.cluster.local/11/api?apikey={{ .PROWLARR_API_KEY }}", // UHDBits
              "http://prowlarr.media.svc.cluster.local/20/api?apikey={{ .PROWLARR_API_KEY }}", // Anthelion
              "http://prowlarr.media.svc.cluster.local/22/api?apikey={{ .PROWLARR_API_KEY }}", // BakaBT
              "http://prowlarr.media.svc.cluster.local/23/api?apikey={{ .PROWLARR_API_KEY }}", // Aither API
              "http://prowlarr.media.svc.cluster.local/24/api?apikey={{ .PROWLARR_API_KEY }}", // Blutopia API
              "http://prowlarr.media.svc.cluster.local/25/api?apikey={{ .PROWLARR_API_KEY }}"  // BeyondHD API
            ],
            notificationWebhookUrls: [
              "https://notifiarr.com/api/v1/notification/crossSeed/{{ .NOTIFIARR_CROSS_SEED_API_KEY }}"
            ],
            dataDirs: [
              "/data/torrents/downloads/seeding/anime-completed",
              "/data/torrents/downloads/seeding/anime-movies-completed",
              "/data/torrents/downloads/seeding/movies-completed",
              "/data/torrents/downloads/seeding/movies-uhd-completed",
              "/data/torrents/downloads/seeding/tv-completed",
              "/data/media/anime",
              "/data/media/anime-movies",
              "/data/media/movies",
              "/data/media/movies-uhd",
              "/data/media/tv",
            ],
            linkDirs: ["/data/torrents/downloads/seeding/cross-seed-data/"],
            outputDir: "/data/torrents/cross-seed",
            host: undefined,
            port: 2468,
            duplicateCategories: false,
            includeNonVideos: false,
            includeSingleEpisodes: false,
            seasonFromEpisodes: 0.8,
            fuzzySizeThreshold: 0.02,
            linkCategory: "cross-seed-data",
            linkType: "hardlink",
            matchMode: "partial",
            maxDataDepth: 2,
            excludeOlder: "8 weeks",
            excludeRecentSearch: "12 days",
            action: "inject",
            rssCadence: "30 minutes",
            searchCadence: "3 days",
            snatchTimeout: "2 minutes",
            searchTimeout: "2 minutes",
            searchLimit: 400,
            blockList: undefined,
          };
  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: notifiarr
    - extract:
        key: prowlarr
    - extract:
        key: radarr
    - extract:
        key: sonarr
